version: '4'
services:
  back_end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8000"
    depends_on:
      - db
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: his_data_base
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:4.8
    environment:
      PGADMIN_DEFAULT_EMAIL: elnazar.ulanbekuulu@outlook.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
