version: '4'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=his_data_base
    ports:
      - "5423:5423"
  pgadmin:
    image: dpage/pgadmin4:4.8
    environment:
      PGADMIN_DEFAULT_EMAIL: elnazar.ulanbekuulu@outlook.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"

volumes:
  postgres_data:
