version: '4'

services:
  web:
    build: ./HIS-back
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
       - ./HIS-back/:/D:/work/DevClub/HIS-Project/HIS-back/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=his_data_base
  pgadmin:
    image: dpage/pgadmin4:4.8
    environment:
      PGADMIN_DEFAULT_EMAIL: elnazar.ulanbekuulu@outlook.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"

volumes:
  postgres_data:
